version: "3.9"
services:
    pg:
        image: "postgres:latest"
        restart: always
        volumes:
            - pg-data:/var/lib/postgresql/data
        env_file: pg.env
    adminer:
        image: "adminer:latest"
        restart: always
        ports:
        - 8080:8080
volumes:
    pg-data:
    pg-logs:
