name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build service
      run: go build -o taskey -v ./cmd/taskey

    - name: Build client
      run: go build -o taskeyd -v ./cmd/taskeyd

    - name: Test
      run: go test -v ./...

    - name: Upload taskey artifacts
      uses: actions/upload-artifact@v2.3.1
      with:
        name: taskey and taskeyd
        path: taskey*
