name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Build service
      run: go build -o taskey -v ./cmd/taskey

    - name: Build daemon
      run: go build -o taskeyd -v ./cmd/taskeyd

    - name: Build cli
      run: go build -o taskey-cli -v ./cmd/taskey-cli

    - name: Test
      run: go test -v ./...

    - name: Upload taskey artifacts
      uses: actions/upload-artifact@v2.3.1
      with:
        name: taskey, taskeyd and taskey-cli
        path: |
          taskey
          taskeyd
          taskey-cli
